//
// Created by Yasuhiro on 05.07.2024.
//

#ifndef ERRORS_H
#define ERRORS_H

#define OK 0
#define GLFW_INIT_ERROR 1
#define GLFW_WINDOW_CREATION_ERROR 2
#define CREATE_VULKAN_INSTANCE_ERROR 3
#define PHYSICAL_DEVICE_NOT_FOUND_ERROR 4
#define LOGICAL_DEVICE_CREATION_ERROR 5
#define CREATE_WINDOW_SURFACE_ERROR 6

#endif //ERRORS_H
